// Ride gallery: loads gallery.json (generated by scripts/generate_gallery_json.py)
// and renders route cards. Stays hidden when the file is absent.

export async function initGallery(onLoadRoute, { shouldAutoLoadFirst = () => false } = {}) {
  try {
    const response = await fetch("./gallery.json");
    if (!response.ok) return;
    const data = await response.json();
    if (!data.routes?.length) return;
    renderGallery(data.routes, onLoadRoute);
    // First visit with nothing loaded yet: start with the first gallery ride
    // instead of an empty map. shouldAutoLoadFirst is re-checked here (after
    // the await) in case a saved ride or a user pick landed in the meantime.
    if (data.routes[0].gpx && shouldAutoLoadFirst()) {
      await onLoadRoute(data.routes[0].gpx, data.routes[0].title);
    }
  } catch {
    // gallery.json not present — gallery stays hidden
  }
}

function renderGallery(routes, onLoadRoute) {
  const section = document.getElementById("gallery");
  const grid = document.getElementById("galleryGrid");
  const browseBtn = document.getElementById("browseGalleryBtn");

  for (const route of routes) {
    const card = document.createElement("article");
    card.className = "gallery-card";

    if (route.screenshot) {
      const img = document.createElement("img");
      img.src = route.screenshot;
      img.alt = route.title;
      img.className = "gallery-card-img";
      img.loading = "lazy";
      card.appendChild(img);
    }

    const body = document.createElement("div");
    body.className = "gallery-card-body";

    const title = document.createElement("h3");
    title.className = "gallery-card-title";
    title.textContent = route.title;

    const desc = document.createElement("p");
    desc.className = "gallery-card-desc";
    desc.innerHTML = route.description
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/\n/g, "<br>");

    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "gallery-card-btn";
    btn.textContent = "Load ride";
    btn.addEventListener("click", () => onLoadRoute(route.gpx, route.title));

    body.appendChild(title);
    body.appendChild(desc);
    body.appendChild(btn);
    card.appendChild(body);
    grid.appendChild(card);
  }

  section.hidden = false;
  browseBtn.hidden = false;
  browseBtn.addEventListener("click", () => {
    section.scrollIntoView({ behavior: "smooth" });
  });
}
