// Ride gallery overlay: loads gallery.json (generated by
// scripts/generate_gallery_json.py) and renders route cards into the
// fullscreen gallery dialog. The "Browse gallery" button stays hidden when
// the file is absent. Everything shown on a card — the grade-colored mini
// elevation profile bars, the distance/terrain/difficulty classification,
// and the distance/ascent/descent totals — is precomputed by the generator
// from the GPX itself; this module only lays it out (distance/ascent/descent
// are formatted here so they follow the km/mi unit setting).

import { formatAltitude, formatDistance } from "./units.mjs";

// Attribution text (Google Maps Photorealistic 3D ToS): the per-card credit
// on each screenshot and the gallery header line. Kept as constants so the
// wording lives in exactly one place.
export const MAP_ATTRIBUTION = "Google";
export const GALLERY_ATTRIBUTION = "screenshots from Google Maps Photorealistic 3D · map data © Google";

// Dot color for the classification, keyed by difficulty label (difficulty.mjs).
const DIFFICULTY_COLORS = {
  "Very Easy": "#4ec06f",
  "Easy": "#4ec06f",
  "Moderate": "#e8b74e",
  "Hard": "#e8823c",
  "Very Hard": "#d9542f",
  "Epic": "#d9542f",
};

const cards = [];
let els = null;

export async function initGallery(onLoadRoute, {
  shouldAutoLoadFirst = () => false,
  getCurrentRouteName = () => null,
  getDistanceUnits = () => "metric",
} = {}) {
  let routes;
  try {
    const response = await fetch("./gallery.json");
    if (!response.ok) return;
    routes = (await response.json()).routes;
  } catch {
    return; // gallery.json not present — gallery stays hidden
  }
  if (!routes?.length) return;

  els = {
    dialog: document.getElementById("galleryDialog"),
    grid: document.getElementById("galleryGrid"),
    count: document.getElementById("galleryCount"),
    attribution: document.getElementById("galleryAttribution"),
    closeBtn: document.getElementById("galleryCloseBtn"),
    browseBtn: document.getElementById("browseGalleryBtn"),
    browseCount: document.getElementById("browseGalleryCount"),
  };

  const loadRoute = async (route) => {
    await onLoadRoute(route.gpx, route.title);
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.close();
  };

  for (const route of routes) {
    els.grid.append(buildCard(route, loadRoute));
  }
  refreshCards(getCurrentRouteName, getDistanceUnits);

  els.count.textContent = `${routes.length} route${routes.length === 1 ? "" : "s"}`;
  els.attribution.textContent = GALLERY_ATTRIBUTION;
  els.browseCount.textContent = String(routes.length);
  els.browseBtn.hidden = false;
  els.browseBtn.addEventListener("click", () => {
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.showModal();
  });
  els.closeBtn.addEventListener("click", () => els.dialog.close());

  // First visit with nothing loaded yet: start with the first gallery ride
  // instead of an empty map. shouldAutoLoadFirst is re-checked here (after
  // the await) in case a saved ride or a user pick landed in the meantime.
  if (routes[0].gpx && shouldAutoLoadFirst()) {
    await onLoadRoute(routes[0].gpx, routes[0].title);
    refreshCards(getCurrentRouteName, getDistanceUnits);
  }
}

// Re-sync the per-card bits that depend on app state: which route is
// currently loaded, and the unit the totals are displayed in.
function refreshCards(getCurrentRouteName, getDistanceUnits) {
  const currentName = getCurrentRouteName();
  const units = getDistanceUnits();
  for (const card of cards) {
    const loaded = card.route.title === currentName;
    card.root.classList.toggle("loaded", loaded);
    card.loadedBadge.hidden = !loaded;
    card.button.textContent = loaded ? "Loaded" : "Load route";
    if (card.distanceStat) {
      card.distanceStat.textContent = formatDistance(card.route.distanceMeters, units, 1);
      card.ascentStat.textContent = formatAltitude(card.route.ascentMeters, units);
      card.descentStat.textContent = formatAltitude(card.route.descentMeters, units);
    }
  }
}

function buildCard(route, loadRoute) {
  const card = document.createElement("article");
  card.className = "gallery-card";

  // thumbnail: screenshot + LOADED badge + attribution credit
  const thumb = document.createElement("div");
  thumb.className = "gallery-card-thumb";
  if (route.screenshot) {
    const img = document.createElement("img");
    img.src = route.screenshot;
    img.alt = route.title;
    img.loading = "lazy";
    thumb.append(img);
  }

  const loadedBadge = document.createElement("div");
  loadedBadge.className = "gallery-card-loaded-badge";
  loadedBadge.textContent = "LOADED";
  loadedBadge.hidden = true;
  thumb.append(loadedBadge);

  const attribution = document.createElement("span");
  attribution.className = "gallery-card-attribution";
  attribution.textContent = MAP_ATTRIBUTION;
  thumb.append(attribution);
  card.append(thumb);

  // precomputed grade-colored mini elevation strip
  if (route.bars?.length) {
    card.append(buildMiniProfile(route.bars));
  }

  // body: title · description · classification + totals · CTA
  const body = document.createElement("div");
  body.className = "gallery-card-body";

  const title = document.createElement("h3");
  title.className = "gallery-card-title";
  title.textContent = route.title;

  const desc = document.createElement("p");
  desc.className = "gallery-card-desc";
  desc.textContent = descriptionText(route);
  body.append(title, desc);

  let distanceStat = null;
  let ascentStat = null;
  let descentStat = null;
  if (route.classification) {
    const c = route.classification;
    const classLine = document.createElement("div");
    classLine.className = "gallery-card-class";
    const dot = document.createElement("i");
    dot.style.background = DIFFICULTY_COLORS[c.difficulty] ?? "#e8b74e";
    const label = document.createElement("span");
    label.textContent = `${c.difficulty} ${c.distanceClass} · ${c.terrainClass}`;
    classLine.append(dot, label);

    const stats = document.createElement("div");
    stats.className = "gallery-card-stats";
    const distance = buildStat("Length", "");
    const ascent = buildStat("Ascent", "accent");
    const descent = buildStat("Descent", "");
    stats.append(distance.wrap, ascent.wrap, descent.wrap);
    distanceStat = distance.stat;
    ascentStat = ascent.stat;
    descentStat = descent.stat;

    body.append(classLine, stats);
  }

  const button = document.createElement("button");
  button.type = "button";
  button.className = "gallery-card-btn";
  button.textContent = "Load route";
  button.addEventListener("click", () => loadRoute(route));
  body.append(button);
  card.append(body);

  cards.push({ route, root: card, loadedBadge, button, distanceStat, ascentStat, descentStat });
  return card;
}

function buildStat(label, valueClass) {
  const wrap = document.createElement("div");
  wrap.className = "gallery-card-stat";
  const name = document.createElement("span");
  name.textContent = label;
  const stat = document.createElement("strong");
  if (valueClass) stat.className = valueClass;
  stat.textContent = "--";
  wrap.append(name, stat);
  return { wrap, stat };
}

function buildMiniProfile(bars) {
  const strip = document.createElement("div");
  strip.className = "gallery-card-profile";
  for (const bar of bars) {
    const el = document.createElement("i");
    el.style.height = `${bar.h}%`;
    el.style.background = bar.c;
    strip.append(el);
  }
  return strip;
}

// Card description: the curated text minus the trailing "**10 km** · …"
// stats line, which the classification + totals below now cover.
function descriptionText(route) {
  const lines = route.description.split("\n").map((line) => line.trim());
  while (lines.length && (lines.at(-1) === "" || /^\*\*[\d.,]/.test(lines.at(-1)))) {
    lines.pop();
  }
  return lines.join(" ").replace(/\*\*/g, "");
}
