// Ride gallery overlay: loads gallery.json (generated by
// scripts/generate_gallery_json.py) and renders route cards into the
// fullscreen gallery dialog. Each card gets a small top-down Leaflet preview
// map (no user interaction — it's just a route thumbnail), auto-framed to
// the route's bounds. Previews are built lazily, the first time the gallery
// dialog is opened.

import { enrichRoute, parseGpx } from "../route/route.mjs";
import {
  GALLERY_PREVIEW_FIT_PADDING_PIXELS,
  GALLERY_PREVIEW_ROUTE_COLOR,
  GALLERY_PREVIEW_ROUTE_WIDTH,
  MAP_ATTRIBUTION,
  MAP_MAX_ZOOM,
  MAP_TILE_SUBDOMAINS,
  MAP_TILE_URL,
} from "../core/tuning.mjs";
import { formatAltitude, formatDistance } from "../core/units.mjs";

export const GALLERY_ATTRIBUTION = "top-down route previews · map data © OpenStreetMap contributors";

const DIFFICULTY_COLORS = {
  "Very Easy": "#4ec06f",
  "Easy": "#4ec06f",
  "Moderate": "#e8b74e",
  "Hard": "#e8823c",
  "Very Hard": "#d9542f",
  "Epic": "#d9542f",
};

const cards = [];
let els = null;
let previewsStarted = false;

export async function initGallery(onLoadRoute, {
  shouldAutoLoadFirst = () => false,
  getRequestedRouteId = () => null,
  getCurrentRouteName = () => null,
  getDistanceUnits = () => "metric",
} = {}) {
  let routes;
  try {
    const response = await fetch("./gallery.json");
    if (!response.ok) return;
    routes = (await response.json()).routes;
  } catch {
    return;
  }
  if (!routes?.length) return;

  els = {
    dialog: document.getElementById("galleryDialog"),
    grid: document.getElementById("galleryGrid"),
    count: document.getElementById("galleryCount"),
    attribution: document.getElementById("galleryAttribution"),
    closeBtn: document.getElementById("galleryCloseBtn"),
    browseBtn: document.getElementById("browseGalleryBtn"),
    browseCount: document.getElementById("browseGalleryCount"),
  };

  const loadRoute = async (route) => {
    await onLoadRoute(route.gpx, route.title, galleryRouteMetadata(route));
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.close();
  };

  for (const route of routes) {
    els.grid.append(buildCard(route, loadRoute));
  }
  refreshCards(getCurrentRouteName, getDistanceUnits);

  els.count.textContent = `${routes.length} route${routes.length === 1 ? "" : "s"}`;
  els.attribution.textContent = GALLERY_ATTRIBUTION;
  els.browseCount.textContent = String(routes.length);
  els.browseBtn.hidden = false;
  els.browseBtn.addEventListener("click", () => {
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.showModal();
    startGalleryPreviews();
  });
  els.closeBtn.addEventListener("click", () => els.dialog.close());

  // A specific route requested via the app URL (e.g. the landing page's
  // "Launch GPX Rider" deep-link, ?route=<id>) always wins over a restored
  // saved ride and over the first-open auto-load. Falls through to the normal
  // behavior when the id is absent or unknown.
  const requestedId = getRequestedRouteId();
  const requested = requestedId ? routes.find((route) => route.id === requestedId) : null;
  if (requested?.gpx) {
    await onLoadRoute(requested.gpx, requested.title, galleryRouteMetadata(requested));
    refreshCards(getCurrentRouteName, getDistanceUnits);
    return;
  }

  if (routes[0].gpx && shouldAutoLoadFirst()) {
    await onLoadRoute(routes[0].gpx, routes[0].title, galleryRouteMetadata(routes[0]));
    refreshCards(getCurrentRouteName, getDistanceUnits);
  }
}

function galleryRouteMetadata(route) {
  return { title: route.title, description: route.description };
}

function refreshCards(getCurrentRouteName, getDistanceUnits) {
  const currentName = getCurrentRouteName();
  const units = getDistanceUnits();
  for (const card of cards) {
    const loaded = card.route.title === currentName;
    card.root.classList.toggle("loaded", loaded);
    card.loadedBadge.hidden = !loaded;
    card.button.textContent = loaded ? "Loaded" : "Load route";
    if (card.distanceStat) {
      card.distanceStat.textContent = formatDistance(card.route.distanceMeters, units, 1);
      card.ascentStat.textContent = formatAltitude(card.route.ascentMeters, units);
      card.descentStat.textContent = formatAltitude(card.route.descentMeters, units);
    }
  }
}

function buildCard(route, loadRoute) {
  const card = document.createElement("article");
  card.className = "gallery-card";

  const thumb = document.createElement("div");
  thumb.className = "gallery-card-thumb";

  const previewMount = document.createElement("div");
  previewMount.className = "gallery-card-map";
  const previewStatus = document.createElement("span");
  previewStatus.className = "gallery-card-preview-status";
  previewStatus.textContent = "Preview loading";
  thumb.append(previewMount, previewStatus);

  const loadedBadge = document.createElement("div");
  loadedBadge.className = "gallery-card-loaded-badge";
  loadedBadge.textContent = "LOADED";
  loadedBadge.hidden = true;
  thumb.append(loadedBadge);
  card.append(thumb);

  const previewTools = document.createElement("div");
  previewTools.className = "gallery-card-preview-tools";
  previewTools.append(buildMiniProfile(route.bars ?? []));
  card.append(previewTools);

  const body = document.createElement("div");
  body.className = "gallery-card-body";

  const title = document.createElement("h3");
  title.className = "gallery-card-title";
  title.textContent = route.title;

  const desc = document.createElement("div");
  desc.className = "gallery-card-desc";
  renderMarkdownDescription(route.description || "", desc);
  body.append(title, desc);

  let distanceStat = null;
  let ascentStat = null;
  let descentStat = null;
  if (route.classification) {
    const c = route.classification;
    const classLine = document.createElement("div");
    classLine.className = "gallery-card-class";
    const dot = document.createElement("i");
    dot.style.background = DIFFICULTY_COLORS[c.difficulty] ?? "#e8b74e";
    const label = document.createElement("span");
    label.textContent = `${c.difficulty} ${c.distanceClass} · ${c.terrainClass}`;
    classLine.append(dot, label);

    const stats = document.createElement("div");
    stats.className = "gallery-card-stats";
    const distance = buildStat("Length", "");
    const ascent = buildStat("Ascent", "accent");
    const descent = buildStat("Descent", "");
    stats.append(distance.wrap, ascent.wrap, descent.wrap);
    distanceStat = distance.stat;
    ascentStat = ascent.stat;
    descentStat = descent.stat;

    body.append(classLine, stats);
  }

  const button = document.createElement("button");
  button.type = "button";
  button.className = "gallery-card-btn";
  button.textContent = "Load route";
  button.addEventListener("click", () => loadRoute(route));
  body.append(button);
  card.append(body);

  cards.push({
    route,
    root: card,
    previewMount,
    previewStatus,
    previewMap: null,
    loadedBadge,
    button,
    distanceStat,
    ascentStat,
    descentStat,
  });
  return card;
}

function startGalleryPreviews() {
  if (previewsStarted) return;
  previewsStarted = true;
  for (const card of cards) {
    void renderCardPreview(card);
  }
}

async function renderCardPreview(card) {
  try {
    const response = await fetch(card.route.gpx);
    if (!response.ok) throw new Error(`Could not load ${card.route.gpx}`);
    const route = enrichRoute(parseGpx(await response.text()).points);
    if (route.length < 2) throw new Error(`Not enough route points in ${card.route.gpx}`);

    const map = L.map(card.previewMount, {
      zoomControl: false,
      attributionControl: false,
      dragging: false,
      scrollWheelZoom: false,
      doubleClickZoom: false,
      touchZoom: false,
      boxZoom: false,
      keyboard: false,
    });
    L.tileLayer(MAP_TILE_URL, {
      subdomains: MAP_TILE_SUBDOMAINS,
      maxZoom: MAP_MAX_ZOOM,
      attribution: MAP_ATTRIBUTION,
    }).addTo(map);
    const bounds = L.latLngBounds(route.map((point) => [point.lat, point.lng]));
    L.polyline(route.map((point) => [point.lat, point.lng]), {
      color: GALLERY_PREVIEW_ROUTE_COLOR,
      weight: GALLERY_PREVIEW_ROUTE_WIDTH,
    }).addTo(map);
    map.fitBounds(bounds, { padding: [GALLERY_PREVIEW_FIT_PADDING_PIXELS, GALLERY_PREVIEW_FIT_PADDING_PIXELS], animate: false });
    card.previewMap = map;
    card.previewStatus.hidden = true;
  } catch (error) {
    console.error(error);
    card.previewStatus.textContent = "Preview unavailable";
  }
}

function buildStat(label, valueClass) {
  const wrap = document.createElement("div");
  wrap.className = "gallery-card-stat";
  const name = document.createElement("span");
  name.textContent = label;
  const stat = document.createElement("strong");
  if (valueClass) stat.className = valueClass;
  stat.textContent = "--";
  wrap.append(name, stat);
  return { wrap, stat };
}

function buildMiniProfile(bars) {
  const strip = document.createElement("div");
  strip.className = "gallery-card-profile";
  for (const bar of bars) {
    const el = document.createElement("i");
    el.style.height = `${bar.h}%`;
    el.style.background = bar.c;
    strip.append(el);
  }
  return strip;
}

function renderMarkdownDescription(text, container) {
  const paragraphs = String(text).trim().split(/\n{2,}/).filter(Boolean);
  container.replaceChildren();
  for (const paragraphText of paragraphs.length ? paragraphs : [""]) {
    const paragraph = document.createElement("p");
    appendInlineMarkdown(paragraph, paragraphText.replace(/\n/g, " "));
    container.append(paragraph);
  }
}

function appendInlineMarkdown(parent, text) {
  const tokenPattern = /(\*\*([^*]+)\*\*|\*([^*]+)\*|\[([^\]]+)\]\((https?:\/\/[^)\s]+)\))/g;
  let lastIndex = 0;
  for (const match of text.matchAll(tokenPattern)) {
    if (match.index > lastIndex) parent.append(document.createTextNode(text.slice(lastIndex, match.index)));
    if (match[2]) {
      const strong = document.createElement("strong");
      strong.textContent = match[2];
      parent.append(strong);
    } else if (match[3]) {
      const em = document.createElement("em");
      em.textContent = match[3];
      parent.append(em);
    } else if (match[4] && match[5]) {
      const link = document.createElement("a");
      link.href = match[5];
      link.target = "_blank";
      link.rel = "noopener";
      link.textContent = match[4];
      parent.append(link);
    }
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) parent.append(document.createTextNode(text.slice(lastIndex)));
}
