// Shared app foundation: the single mutable `state` object, the DOM element
// map `els`, and the status-line helper every feature module reports through.
// This module is the bottom of the app's import graph — it must never import
// a feature module (only pure/leaf modules like tuning.mjs and eta.mjs), so
// any feature module can import it without creating an eval-time cycle.

import { createRideEstimator } from "../ride/eta.mjs";
import {
  DEFAULT_DURATION_FORMAT,
  DEFAULT_GRADE_INTERVAL_SECONDS,
  DEFAULT_HUD_DOCK_COLLAPSED,
  DEFAULT_HUD_FIELD_ORDER,
  DEFAULT_HUD_VISIBLE_COUNT,
  DEFAULT_MAX_HEART_RATE_BPM,
  DEFAULT_RESTING_HEART_RATE_BPM,
  DEFAULT_ROUTE_GRADE_COLORS_ENABLED,
  DEFAULT_SCREENSHOT_ASPECT,
  DEFAULT_SCREENSHOT_WIDTH,
  DEFAULT_SHOW_SCREENSHOT_BUTTON,
  DEFAULT_THEATER_HIDE_CLIMB_BANNER,
  DEFAULT_THEATER_HIDE_CLOCK,
  DEFAULT_THEATER_HIDE_CONTROLS,
  DEFAULT_THEATER_HIDE_DEMO_CHIP,
  DEFAULT_THEATER_HIDE_DOCK,
  DEFAULT_THEATER_HIDE_METERS,
  DEFAULT_TIME_FORMAT,
} from "./tuning.mjs";

export const state = {
  route: [],
  // Display name shown above the route classification: a gallery ride's
  // curated title, else the GPX's own <name>, else the uploaded filename.
  routeName: null,
  // Source metadata for a library route. Gallery export keeps this content
  // intact and replaces only its preview camera with the live map camera.
  galleryMetadata: null,
  // Detected climbs for the loaded route (see climbs.mjs), recomputed once
  // per route load in updateRouteOverview and read every ride tick to drive
  // the live "current climb" / "next climb" status.
  climbs: [],
  progressMeters: 0,
  simulating: false,
  pedaling: false,
  movementLoopActive: false,
  tickRaf: null,
  tickTimeout: null,
  lastTick: 0,
  routeLines: [],
  riderMarker: null,
  // The Leaflet map instance (see map/map-init.mjs).
  map: null,
  trainerSpeedKph: null,
  trainerPowerWatts: null,
  trainerCadenceRpm: null,
  trainerCaloriesKcal: null,
  powerCaloriesKcal: 0,
  trainerHeartRateBpm: null,
  strapHeartRateBpm: null,
  heartRateStatusText: null,
  heartRateRefreshTimer: null,
  demoModeActive: false,
  demoModel: null,
  demoHistorySamples: [],
  demoTimerSeconds: 0,
  demoCaloriesKcal: 0,
  gradeUpdateIntervalSeconds: DEFAULT_GRADE_INTERVAL_SECONDS,
  lastSlowUiAt: 0,
  lastRideSavedAt: 0,
  profileHoverMeters: null,
  profileSelectStartMeters: null,
  profileSelectStartX: null,
  profileSelectPointerId: null,
  profileSelecting: false,
  profileSelectionSuppressClick: false,
  selectedProfileSegment: null,
  // "overview" while the whole route (or a focused climb/segment) is fitted
  // into view, "manual" after the user drags/zooms the map by hand, "follow"
  // once movement starts (see map/map-view.mjs).
  mapMode: "follow",
  // True while a setView/fitBounds/panTo call we made ourselves is in
  // flight, so the drag/zoom listeners that detect a *manual* map grab don't
  // mistake our own programmatic moves for one.
  programmaticMapMove: false,
  overviewActive: false,
  // The route (whole route, or a focused climb/segment slice) the map is
  // currently fitted to while in overview mode.
  overviewRoute: null,
  focusedClimbIndex: null,
  // Auto-pan the map to the rider's position while riding (the map action bar
  // "keep rider centered" toggle). Turning it off leaves the map wherever the
  // user left it.
  followRider: true,
  screenshotInProgress: false,
  showScreenshotButton: DEFAULT_SHOW_SCREENSHOT_BUTTON,
  screenshotAspect: DEFAULT_SCREENSHOT_ASPECT,
  screenshotWidth: DEFAULT_SCREENSHOT_WIDTH,
  routeGradeColorsEnabled: DEFAULT_ROUTE_GRADE_COLORS_ENABLED,
  mapFullscreen: false,
  theaterMode: false,
  theaterHideClock: DEFAULT_THEATER_HIDE_CLOCK,
  theaterHideMeters: DEFAULT_THEATER_HIDE_METERS,
  theaterHideDock: DEFAULT_THEATER_HIDE_DOCK,
  theaterHideClimbBanner: DEFAULT_THEATER_HIDE_CLIMB_BANNER,
  theaterHideDemoChip: DEFAULT_THEATER_HIDE_DEMO_CHIP,
  theaterHideControls: DEFAULT_THEATER_HIDE_CONTROLS,
  distanceUnits: "metric",
  energyUnits: "kcal",
  timeFormat: DEFAULT_TIME_FORMAT,
  durationFormat: DEFAULT_DURATION_FORMAT,
  restingHeartRateBpm: DEFAULT_RESTING_HEART_RATE_BPM,
  maxHeartRateBpm: DEFAULT_MAX_HEART_RATE_BPM,
  ftpWatts: null,
  draggedHudField: null,
  fullscreenClockTimer: null,
  hudFieldOrder: [...DEFAULT_HUD_FIELD_ORDER],
  hudVisibleCount: DEFAULT_HUD_VISIBLE_COUNT,
  hudDockCollapsed: DEFAULT_HUD_DOCK_COLLAPSED,
  profileSeries: { speed: true, power: true, heartRate: true },
  // startDistance of the climb whose mini-profile is currently drawn in the
  // banner, so it is only rebuilt when the upcoming climb changes.
  bannerClimbKey: null,
  // Per-session pace tracker feeding the smart ETA; reset on new GPX load.
  rideEstimator: createRideEstimator(),
};

export const els = {
  brandName: document.querySelector("#brandName"),
  settingsBtn: document.querySelector("#settingsBtn"),
  mapSettingsShortcutBtn: document.querySelector("#mapSettingsShortcutBtn, #fullscreenSettingsBtn"),
  settingsDialog: document.querySelector("#settingsDialog"),
  settingsCloseBtn: document.querySelector("#settingsCloseBtn"),
  settingsDoneBtn: document.querySelector("#settingsDoneBtn"),
  settingsTabs: document.querySelectorAll("#settingsDialog [data-settings-tab]"),
  settingsPanels: document.querySelectorAll("#settingsDialog [data-settings-panel]"),
  settingsPanelTitle: document.querySelector("#settingsPanelTitle"),
  settingsPanelSubtitle: document.querySelector("#settingsPanelSubtitle"),
  gpxFile: document.querySelector("#gpxFile"),
  gpxChip: document.querySelector("#gpxChip"),
  gpxChipName: document.querySelector("#gpxChipName"),
  difficultyStat: document.querySelector("#difficultyStat"),
  difficultyDetail: document.querySelector("#difficultyDetail"),
  galleryDialog: document.querySelector("#galleryDialog"),
  climbsSection: document.querySelector("#climbsSection"),
  climbStatus: document.querySelector("#climbStatus"),
  climbStatusHeadline: document.querySelector("#climbStatusHeadline"),
  climbStatusDetail: document.querySelector("#climbStatusDetail"),
  climbsList: document.querySelector("#climbsList"),
  distanceStat: document.querySelector("#distanceStat"),
  riddenStat: document.querySelector("#riddenStat"),
  remainingStat: document.querySelector("#remainingStat"),
  etaStat: document.querySelector("#etaStat"),
  ascentStat: document.querySelector("#ascentStat"),
  descentStat: document.querySelector("#descentStat"),
  ascentLeftStat: document.querySelector("#ascentLeftStat"),
  gradeStat: document.querySelector("#gradeStat"),
  altitudeStat: document.querySelector("#altitudeStat"),
  powerStat: document.querySelector("#powerStat"),
  speedStat: document.querySelector("#speedStat"),
  trainerStat: document.querySelector("#trainerStat"),
  heartRateStat: document.querySelector("#heartRateStat"),
  caloriesStat: document.querySelector("#caloriesStat"),
  speedInput: document.querySelector("#speedInput"),
  speedOutput: document.querySelector("#speedOutput"),
  gradeIntervalInput: document.querySelector("#gradeIntervalInput"),
  gradeIntervalOutput: document.querySelector("#gradeIntervalOutput"),
  distanceUnitSelect: document.querySelector("#distanceUnitSelect"),
  energyUnitSelect: document.querySelector("#energyUnitSelect"),
  timeFormatSelect: document.querySelector("#timeFormatSelect"),
  durationFormatSelect: document.querySelector("#durationFormatSelect"),
  centerRiderInput: document.querySelector("#centerRiderInput"),
  routeGradeColorsInput: document.querySelector("#routeGradeColorsInput"),
  resetRenderingBtn: document.querySelector("#resetRenderingBtn"),
  connectBtn: document.querySelector("#connectBtn"),
  connectHrBtn: document.querySelector("#connectHrBtn"),
  demoModeBtn: document.querySelector("#demoModeBtn"),
  resizeRecordingWindowBtn: document.querySelector("#resizeRecordingWindowBtn"),
  theaterHudTogglesLabel: document.querySelector(".theater-hud-toggles-label"),
  theaterHideClockInput: document.querySelector("#theaterHideClockInput"),
  theaterHideMetersInput: document.querySelector("#theaterHideMetersInput"),
  theaterHideDockInput: document.querySelector("#theaterHideDockInput"),
  theaterHideClimbBannerInput: document.querySelector("#theaterHideClimbBannerInput"),
  theaterHideDemoChipInput: document.querySelector("#theaterHideDemoChipInput"),
  theaterHideControlsInput: document.querySelector("#theaterHideControlsInput"),
  demoBanner: document.querySelector("#demoBanner"),
  restingHeartRateInput: document.querySelector("#restingHeartRateInput"),
  maxHeartRateInput: document.querySelector("#maxHeartRateInput"),
  ftpInput: document.querySelector("#ftpInput"),
  powerZoneSummary: document.querySelector("#powerZoneSummary"),
  heartRateZoneSummary: document.querySelector("#heartRateZoneSummary"),
  zoneHelpButtons: document.querySelectorAll("[data-zone-help-trigger]"),
  startBtn: document.querySelector("#startBtn"),
  startBtnLabel: document.querySelector("#startBtnLabel"),
  resetBtn: document.querySelector("#resetBtn"),
  trainerDot: document.querySelector("#trainerDot"),
  hrDot: document.querySelector("#hrDot"),
  hrConnectionStat: document.querySelector("#hrConnectionStat"),
  recIndicator: document.querySelector("#recIndicator"),
  centerRiderBtn: document.querySelector("#centerRiderBtn"),
  progress: document.querySelector("#progress"),
  progressLabel: document.querySelector("#progressLabel"),
  ascentProgress: document.querySelector("#ascentProgress"),
  ascentProgressLabel: document.querySelector("#ascentProgressLabel"),
  profile: document.querySelector("#profile"),
  mapViewport: document.querySelector("#mapViewport"),
  mapActions: document.querySelector(".map-actions"),
  map: document.querySelector("#map"),
  fullscreenBtn: document.querySelector("#fullscreenBtn"),
  mapOverviewControl: document.querySelector("#mapOverviewControl"),
  overviewToggleBtn: document.querySelector("#overviewToggleBtn"),
  climbOverviewControl: document.querySelector("#climbOverviewControl"),
  climbOverviewToggleBtn: document.querySelector("#climbOverviewToggleBtn"),
  screenshotBtn: document.querySelector("#screenshotBtn"),
  screenshotButtonInput: document.querySelector("#screenshotButtonInput"),
  screenshotAspectSelect: document.querySelector("#screenshotAspectSelect"),
  screenshotWidthSelect: document.querySelector("#screenshotWidthSelect"),
  galleryTitleInput: document.querySelector("#galleryTitleInput"),
  galleryDescriptionInput: document.querySelector("#galleryDescriptionInput"),
  galleryMetadataOutput: document.querySelector("#galleryMetadataOutput"),
  copyGalleryMetadataBtn: document.querySelector("#copyGalleryMetadataBtn"),
  fullscreenOverlayBottom: document.querySelector("#fullscreenOverlayBottom"),
  hudPowerStat: document.querySelector("#hudPowerStat"),
  hudSpeedStat: document.querySelector("#hudSpeedStat"),
  hudHeartRateStat: document.querySelector("#hudHeartRateStat"),
  hudGradeStat: document.querySelector("#hudGradeStat"),
  hudRiddenStat: document.querySelector("#hudRiddenStat"),
  hudRemainingStat: document.querySelector("#hudRemainingStat"),
  hudAscentLeftStat: document.querySelector("#hudAscentLeftStat"),
  hudEtaStat: document.querySelector("#hudEtaStat"),
  hudCaloriesStat: document.querySelector("#hudCaloriesStat"),
  hudAltitudeStat: document.querySelector("#hudAltitudeStat"),
  hudAscentStat: document.querySelector("#hudAscentStat"),
  hudElapsedStat: document.querySelector("#hudElapsedStat"),
  hudTiles: document.querySelectorAll("#fullscreenHud [data-hud]"),
  hudOrderList: document.querySelector("#hudOrderList"),
  hudVisibleCountOutput: document.querySelector("#hudVisibleCountOutput"),
  hudLessBtn: document.querySelector("#hudLessBtn"),
  hudMoreBtn: document.querySelector("#hudMoreBtn"),
  hudSettingsBtn: document.querySelector("#hudSettingsBtn"),
  hudVisibleLessBtn: document.querySelector("#hudVisibleLessBtn"),
  hudVisibleMoreBtn: document.querySelector("#hudVisibleMoreBtn"),
  fullscreenHud: document.querySelector("#fullscreenHud"),
  profileSeriesButtons: document.querySelectorAll("[data-profile-series]"),
  // Fullscreen HUD: data dock, top-left clock chip, and top-center climb banner
  dockToggleBtn: document.querySelector("#dockToggleBtn"),
  fsProfileMount: document.querySelector("#fsProfileMount"),
  fsRoadRouteName: document.querySelector("#fsRoadRouteName"),
  fsRoadRouteProps: document.querySelector("#fsRoadRouteProps"),
  fsDistLabel: document.querySelector("#fsDistLabel"),
  fsDistFill: document.querySelector("#fsDistFill"),
  fsClimbLabel: document.querySelector("#fsClimbLabel"),
  fsClimbFill: document.querySelector("#fsClimbFill"),
  fullscreenClock: document.querySelector("#fullscreenClock"),
  fsClockLocal: document.querySelector("#fsClockLocal"),
  fsClockElapsed: document.querySelector("#fsClockElapsed"),
  fsClockDistance: document.querySelector("#fsClockDistance"),
  fsClockAscent: document.querySelector("#fsClockAscent"),
  fullscreenTrainingMeters: document.querySelector("#fullscreenTrainingMeters"),
  powerMeter: document.querySelector("#powerMeter"),
  heartRateMeter: document.querySelector("#heartRateMeter"),
  gradeMeter: document.querySelector("#gradeMeter"),
  cadenceMeter: document.querySelector("#cadenceMeter"),
  zonePowerValue: document.querySelector("#zonePowerValue"),
  zonePowerMeta: document.querySelector("#zonePowerMeta"),
  zonePowerFill: document.querySelector("#zonePowerFill"),
  zoneHeartRateValue: document.querySelector("#zoneHeartRateValue"),
  zoneHeartRateMeta: document.querySelector("#zoneHeartRateMeta"),
  zoneHeartRateFill: document.querySelector("#zoneHeartRateFill"),
  zoneGradeValue: document.querySelector("#zoneGradeValue"),
  zoneGradeMeta: document.querySelector("#zoneGradeMeta"),
  zoneGradeFill: document.querySelector("#zoneGradeFill"),
  zoneCadenceValue: document.querySelector("#zoneCadenceValue"),
  zoneCadenceMeta: document.querySelector("#zoneCadenceMeta"),
  zoneCadenceFill: document.querySelector("#zoneCadenceFill"),
  climbBanner: document.querySelector("#climbBanner"),
  climbBannerAhead: document.querySelector("#climbBannerAhead"),
  climbBannerOn: document.querySelector("#climbBannerOn"),
  segmentBanner: document.querySelector("#segmentBanner"),
  cbCategory: document.querySelector("#cbCategory"),
  cbAheadOrder: document.querySelector("#cbAheadOrder"),
  cbOnOrder: document.querySelector("#cbOnOrder"),
  cbInDist: document.querySelector("#cbInDist"),
  cbInUnit: document.querySelector("#cbInUnit"),
  cbMini: document.querySelector("#cbMini"),
  cbBaseAlt: document.querySelector("#cbBaseAlt"),
  cbPeakAltMini: document.querySelector("#cbPeakAltMini"),
  cbLen: document.querySelector("#cbLen"),
  cbGain: document.querySelector("#cbGain"),
  cbAvg: document.querySelector("#cbAvg"),
  cbMax: document.querySelector("#cbMax"),
  cbToTop: document.querySelector("#cbToTop"),
  cbToGo: document.querySelector("#cbToGo"),
  cbCurAlt: document.querySelector("#cbCurAlt"),
  cbPeakAlt: document.querySelector("#cbPeakAlt"),
  cbGradeLeft: document.querySelector("#cbGradeLeft"),
  cbDistFill: document.querySelector("#cbDistFill"),
  cbAscFill: document.querySelector("#cbAscFill"),
  sbStart: document.querySelector("#sbStart"),
  sbEnd: document.querySelector("#sbEnd"),
  sbLen: document.querySelector("#sbLen"),
  sbAsc: document.querySelector("#sbAsc"),
  sbDesc: document.querySelector("#sbDesc"),
  recDistanceStat: document.querySelector("#recDistanceStat"),
  recTimeStat: document.querySelector("#recTimeStat"),
  recPointsStat: document.querySelector("#recPointsStat"),
  recHeartRateStat: document.querySelector("#recHeartRateStat"),
  recCaloriesStat: document.querySelector("#recCaloriesStat"),
  downloadFitBtn: document.querySelector("#downloadFitBtn"),
  clearRideDataBtn: document.querySelector("#clearRideDataBtn"),
};

// One-line status readout under the progress bar; the app-wide way to tell
// the user what just happened (load errors, save notices, mode changes).
export function updateProgressLabel(text) {
  els.progressLabel.textContent = text;
}
