// GPX Rider tuning loader. THE VALUES AND THEIR DOCUMENTATION LIVE IN
// tuning.yaml (same folder) — edit that file, reload the page, done. This
// module only loads and re-exports them under their historical names so the
// rest of the app keeps importing plain constants, and so the Python
// generators (scripts/tuning_config.py) can read the exact same file instead
// of mirroring values by hand.
//
// Top-level await: importers simply wait until the config is loaded — no
// init call needed anywhere. In the browser the file is fetched relative to
// this module; under Node (tests, tooling) it is read from disk.

import { parseYaml } from "./yaml.mjs";

const CONFIG_URL = new URL("./tuning.yaml", import.meta.url);

async function loadConfigText() {
  // Node (tests, link checks, tooling) has no fetch for file: URLs.
  if (globalThis.process?.versions?.node) {
    const { readFile } = await import("node:fs/promises");
    const { fileURLToPath } = await import("node:url");
    return readFile(fileURLToPath(CONFIG_URL), "utf8");
  }
  const response = await fetch(CONFIG_URL);
  if (!response.ok) throw new Error(`Could not load tuning.yaml (${response.status}).`);
  return response.text();
}

const config = parseYaml(await loadConfigText());

// Every export is looked up strictly: a typo or a missing key in tuning.yaml
// fails loudly at startup instead of silently becoming undefined somewhere
// deep in the app.
function req(name) {
  if (!(name in config)) throw new Error(`tuning.yaml is missing "${name}".`);
  return config[name];
}

export const APP_NAME = req("APP_NAME");

// Movement & pedaling
export const PEDALING_START_KPH = req("PEDALING_START_KPH");
export const PEDALING_STOP_KPH = req("PEDALING_STOP_KPH");
export const SIMULATION_SPEED_MIN_KPH = req("SIMULATION_SPEED_MIN_KPH");
export const SIMULATION_SPEED_MAX_KPH = req("SIMULATION_SPEED_MAX_KPH");
export const DEFAULT_SIMULATION_SPEED_KPH = req("DEFAULT_SIMULATION_SPEED_KPH");
export const MAX_TICK_SECONDS = req("MAX_TICK_SECONDS");
export const SLOW_UI_INTERVAL_MS = req("SLOW_UI_INTERVAL_MS");
export const RIDE_SAVE_THROTTLE_MS = req("RIDE_SAVE_THROTTLE_MS");

// Trainer grade updates
export const DEFAULT_GRADE_INTERVAL_SECONDS = req("DEFAULT_GRADE_INTERVAL_SECONDS");
export const GRADE_INTERVAL_MIN_SECONDS = req("GRADE_INTERVAL_MIN_SECONDS");
export const GRADE_INTERVAL_MAX_SECONDS = req("GRADE_INTERVAL_MAX_SECONDS");

// Route math
export const GRADE_LOOKAROUND_METERS = req("GRADE_LOOKAROUND_METERS");
export const GRADE_MIN_PERCENT = req("GRADE_MIN_PERCENT");
export const GRADE_MAX_PERCENT = req("GRADE_MAX_PERCENT");
export const GRADE_METER_MIN_PERCENT = req("GRADE_METER_MIN_PERCENT");
export const GRADE_METER_MAX_PERCENT = req("GRADE_METER_MAX_PERCENT");
export const CLIMB_NOISE_THRESHOLD_METERS = req("CLIMB_NOISE_THRESHOLD_METERS");

// Grade color palette (shared with the Python gallery generator)
export const GRADE_PROFILE_THRESHOLDS = req("GRADE_PROFILE_THRESHOLDS");
export const GRADE_PROFILE_COLORS = req("GRADE_PROFILE_COLORS");

// Smart ETA
export const ETA_CLIMB_EQUIVALENT_FACTOR = req("ETA_CLIMB_EQUIVALENT_FACTOR");
export const ETA_DESCENT_CREDIT_FACTOR = req("ETA_DESCENT_CREDIT_FACTOR");
export const ETA_MIN_HISTORY_SECONDS = req("ETA_MIN_HISTORY_SECONDS");
export const ETA_MIN_HISTORY_METERS = req("ETA_MIN_HISTORY_METERS");

// Camera defaults & bounds
export const DEFAULT_CAMERA_ZOOM = req("DEFAULT_CAMERA_ZOOM");
export const DEFAULT_CAMERA_ANGLE_DEGREES = req("DEFAULT_CAMERA_ANGLE_DEGREES");
export const DEFAULT_CAMERA_BEHIND_METERS = req("DEFAULT_CAMERA_BEHIND_METERS");
export const DEFAULT_FIRST_PERSON_CAMERA_HEIGHT_METERS = req("DEFAULT_FIRST_PERSON_CAMERA_HEIGHT_METERS");
export const FIRST_PERSON_CAMERA_HEIGHT_MIN_METERS = req("FIRST_PERSON_CAMERA_HEIGHT_MIN_METERS");
export const FIRST_PERSON_CAMERA_HEIGHT_MAX_METERS = req("FIRST_PERSON_CAMERA_HEIGHT_MAX_METERS");
export const FIRST_PERSON_LOOK_AHEAD_METERS = req("FIRST_PERSON_LOOK_AHEAD_METERS");
export const FIRST_PERSON_CAMERA_TILT_DEGREES = req("FIRST_PERSON_CAMERA_TILT_DEGREES");
export const OVERVIEW_TILT_DEGREES = req("OVERVIEW_TILT_DEGREES");
export const OVERVIEW_HEADING_OFFSET_DEGREES = req("OVERVIEW_HEADING_OFFSET_DEGREES");
export const OVERVIEW_MARGIN_FACTOR = req("OVERVIEW_MARGIN_FACTOR");
export const OVERVIEW_RANGE_FACTOR = req("OVERVIEW_RANGE_FACTOR");
export const OVERVIEW_MIN_RANGE_METERS = req("OVERVIEW_MIN_RANGE_METERS");
export const OVERVIEW_MAX_RANGE_METERS = req("OVERVIEW_MAX_RANGE_METERS");

// Overview motion
export const DEFAULT_OVERVIEW_MODE = req("DEFAULT_OVERVIEW_MODE");
export const DEFAULT_CLIMB_FOCUS_MODE = req("DEFAULT_CLIMB_FOCUS_MODE");
export const OVERVIEW_ORBIT_SECONDS_PER_REV = req("OVERVIEW_ORBIT_SECONDS_PER_REV");
export const OVERVIEW_ORBIT_DIRECTION = req("OVERVIEW_ORBIT_DIRECTION");
export const DEFAULT_CLIMB_ORBIT_SECONDS_PER_REV = req("DEFAULT_CLIMB_ORBIT_SECONDS_PER_REV");
export const CLIMB_ORBIT_SECONDS_PER_REV_MIN = req("CLIMB_ORBIT_SECONDS_PER_REV_MIN");
export const CLIMB_ORBIT_SECONDS_PER_REV_MAX = req("CLIMB_ORBIT_SECONDS_PER_REV_MAX");

// Finish-line orbit
export const DEFAULT_FINISH_ORBIT_ENABLED = req("DEFAULT_FINISH_ORBIT_ENABLED");
export const FINISH_ORBIT_RANGE_METERS = req("FINISH_ORBIT_RANGE_METERS");
export const FINISH_ORBIT_TILT_DEGREES = req("FINISH_ORBIT_TILT_DEGREES");
export const FINISH_ORBIT_SECONDS_PER_REV = req("FINISH_ORBIT_SECONDS_PER_REV");
export const FINISH_ORBIT_DIRECTION = req("FINISH_ORBIT_DIRECTION");
export const FINISH_ORBIT_LOOKAT_HEIGHT_METERS = req("FINISH_ORBIT_LOOKAT_HEIGHT_METERS");

// Profile segment selection
export const PROFILE_SEGMENT_SELECTION_DRAG_PIXELS = req("PROFILE_SEGMENT_SELECTION_DRAG_PIXELS");
export const PROFILE_SEGMENT_SELECTION_MIN_METERS = req("PROFILE_SEGMENT_SELECTION_MIN_METERS");
export const PROFILE_SEGMENT_SELECTION_MIN_ROUTE_FRACTION = req("PROFILE_SEGMENT_SELECTION_MIN_ROUTE_FRACTION");

// Overview debug line
export const OVERVIEW_DEBUG_LINE_COLOR = req("OVERVIEW_DEBUG_LINE_COLOR");
export const OVERVIEW_DEBUG_LINE_WIDTH = req("OVERVIEW_DEBUG_LINE_WIDTH");
export const OVERVIEW_DEBUG_LINE_ALTITUDE_METERS = req("OVERVIEW_DEBUG_LINE_ALTITUDE_METERS");
export const OVERVIEW_DEBUG_LINE_SAMPLE_COUNT = req("OVERVIEW_DEBUG_LINE_SAMPLE_COUNT");

export const DEFAULT_MAP_FOV_DEGREES = req("DEFAULT_MAP_FOV_DEGREES");
export const OVERVIEW_ANIM_INTRO_SECONDS = req("OVERVIEW_ANIM_INTRO_SECONDS");
export const SATELLITE_TILT_DEGREES = req("SATELLITE_TILT_DEGREES");
export const SATELLITE_MARGIN_FACTOR = req("SATELLITE_MARGIN_FACTOR");
export const ELLIPSE_FLYBY = req("ELLIPSE_FLYBY");
export const HEADING_SAMPLE_METERS = req("HEADING_SAMPLE_METERS");
export const INTERACTION_SETTLE_MS = req("INTERACTION_SETTLE_MS");
export const CAMERA_ZOOM_MIN = req("CAMERA_ZOOM_MIN");
export const CAMERA_ZOOM_MAX = req("CAMERA_ZOOM_MAX");
export const CAMERA_PAN_LIMIT_METERS = req("CAMERA_PAN_LIMIT_METERS");
export const CAMERA_CENTER_ALTITUDE_LIMIT_METERS = req("CAMERA_CENTER_ALTITUDE_LIMIT_METERS");
export const CAMERA_TILT_MIN = req("CAMERA_TILT_MIN");
export const CAMERA_TILT_MAX = req("CAMERA_TILT_MAX");

// Camera terrain avoidance
export const DEFAULT_TERRAIN_AVOID_ENABLED = req("DEFAULT_TERRAIN_AVOID_ENABLED");
export const DEFAULT_TERRAIN_CLEARANCE_METERS = req("DEFAULT_TERRAIN_CLEARANCE_METERS");
export const TERRAIN_SAMPLE_RADIUS_METERS = req("TERRAIN_SAMPLE_RADIUS_METERS");
export const TERRAIN_LIFT_RECOMPUTE_MS = req("TERRAIN_LIFT_RECOMPUTE_MS");
export const TERRAIN_LIFT_RISE_TAU_SECONDS = req("TERRAIN_LIFT_RISE_TAU_SECONDS");
export const TERRAIN_LIFT_FALL_TAU_SECONDS = req("TERRAIN_LIFT_FALL_TAU_SECONDS");

// Rider beacon
export const DEFAULT_BEACON_ENABLED = req("DEFAULT_BEACON_ENABLED");
export const DEFAULT_BEACON_DIAMETER_METERS = req("DEFAULT_BEACON_DIAMETER_METERS");
export const DEFAULT_BEACON_HEIGHT_METERS = req("DEFAULT_BEACON_HEIGHT_METERS");
export const DEFAULT_BEACON_OPACITY = req("DEFAULT_BEACON_OPACITY");
export const DEFAULT_BEACON_COLOR = req("DEFAULT_BEACON_COLOR");

// Rider dot
export const RIDER_DOT_MODEL_PATH = req("RIDER_DOT_MODEL_PATH");
export const RIDER_DOT_ORIENTATION = req("RIDER_DOT_ORIENTATION");
export const RIDER_DOT_SCALE = req("RIDER_DOT_SCALE");
export const RIDER_DOT_OVERVIEW_SCALE_FACTOR = req("RIDER_DOT_OVERVIEW_SCALE_FACTOR");
export const RIDER_DOT_DIAMETER_METERS = req("RIDER_DOT_DIAMETER_METERS");
export const RIDER_DOT_ALTITUDE_METERS = req("RIDER_DOT_ALTITUDE_METERS");

// Route line rendering
export const DEFAULT_ROUTE_GRADE_COLORS_ENABLED = req("DEFAULT_ROUTE_GRADE_COLORS_ENABLED");
export const ROUTE_LINE_ALTITUDE_METERS = req("ROUTE_LINE_ALTITUDE_METERS");
export const ROUTE_LINE_COLOR = req("ROUTE_LINE_COLOR");
export const ROUTE_LINE_WIDTH = req("ROUTE_LINE_WIDTH");
export const ROUTE_LINE_OUTER_COLOR = req("ROUTE_LINE_OUTER_COLOR");
export const ROUTE_LINE_OUTER_WIDTH = req("ROUTE_LINE_OUTER_WIDTH");
export const ROUTE_FOCUS_LINE_WIDTH = req("ROUTE_FOCUS_LINE_WIDTH");
export const ROUTE_FOCUS_OUTER_COLOR = req("ROUTE_FOCUS_OUTER_COLOR");
export const ROUTE_FOCUS_OUTER_WIDTH = req("ROUTE_FOCUS_OUTER_WIDTH");
export const ROUTE_LINE_SPACING_METERS = req("ROUTE_LINE_SPACING_METERS");
export const ROUTE_LINE_MAX_POINTS = req("ROUTE_LINE_MAX_POINTS");

// Gallery previews & mini profiles
export const GALLERY_PREVIEW_MAP_TYPE = req("GALLERY_PREVIEW_MAP_TYPE");
export const GALLERY_PREVIEW_FIT_PADDING_PIXELS = req("GALLERY_PREVIEW_FIT_PADDING_PIXELS");
export const GALLERY_PREVIEW_ROUTE_COLOR = req("GALLERY_PREVIEW_ROUTE_COLOR");
export const GALLERY_PREVIEW_2D_ROUTE_WIDTH = req("GALLERY_PREVIEW_2D_ROUTE_WIDTH");
export const GALLERY_PREVIEW_3D_ROUTE_WIDTH = req("GALLERY_PREVIEW_3D_ROUTE_WIDTH");
export const GALLERY_PREVIEW_3D_ROUTE_OUTER_COLOR = req("GALLERY_PREVIEW_3D_ROUTE_OUTER_COLOR");
export const GALLERY_PREVIEW_3D_ROUTE_OUTER_WIDTH = req("GALLERY_PREVIEW_3D_ROUTE_OUTER_WIDTH");
export const GALLERY_MINI_PROFILE_BAR_COUNT = req("GALLERY_MINI_PROFILE_BAR_COUNT");
export const GALLERY_MINI_PROFILE_FLAT_COLOR = req("GALLERY_MINI_PROFILE_FLAT_COLOR");

// Screenshots & theater mode
export const DEFAULT_SHOW_SCREENSHOT_BUTTON = req("DEFAULT_SHOW_SCREENSHOT_BUTTON");
export const DEFAULT_SCREENSHOT_ASPECT = req("DEFAULT_SCREENSHOT_ASPECT");
export const DEFAULT_SCREENSHOT_WIDTH = req("DEFAULT_SCREENSHOT_WIDTH");
export const SCREENSHOT_WIDTH_MIN = req("SCREENSHOT_WIDTH_MIN");
export const SCREENSHOT_WIDTH_MAX = req("SCREENSHOT_WIDTH_MAX");
export const RECORDING_MAP_VIEWPORT_WIDTH_PIXELS = req("RECORDING_MAP_VIEWPORT_WIDTH_PIXELS");
export const RECORDING_MAP_VIEWPORT_HEIGHT_PIXELS = req("RECORDING_MAP_VIEWPORT_HEIGHT_PIXELS");
export const RECORDING_MAP_VIEWPORT_TOLERANCE_PIXELS = req("RECORDING_MAP_VIEWPORT_TOLERANCE_PIXELS");
export const DEFAULT_THEATER_HIDE_CLOCK = req("DEFAULT_THEATER_HIDE_CLOCK");
export const DEFAULT_THEATER_HIDE_METERS = req("DEFAULT_THEATER_HIDE_METERS");
export const DEFAULT_THEATER_HIDE_DOCK = req("DEFAULT_THEATER_HIDE_DOCK");
export const DEFAULT_THEATER_HIDE_CLIMB_BANNER = req("DEFAULT_THEATER_HIDE_CLIMB_BANNER");
export const DEFAULT_THEATER_HIDE_DEMO_CHIP = req("DEFAULT_THEATER_HIDE_DEMO_CHIP");
export const DEFAULT_THEATER_HIDE_CONTROLS = req("DEFAULT_THEATER_HIDE_CONTROLS");
export const DEFAULT_THEATER_HIDE_MINIMAP = req("DEFAULT_THEATER_HIDE_MINIMAP");

// Display & HUD defaults
export const DEFAULT_SHOW_MINIMAP = req("DEFAULT_SHOW_MINIMAP");
export const DEFAULT_MAP_LABELS_ENABLED = req("DEFAULT_MAP_LABELS_ENABLED");
export const DEFAULT_TIME_FORMAT = req("DEFAULT_TIME_FORMAT");
export const DEFAULT_DURATION_FORMAT = req("DEFAULT_DURATION_FORMAT");
export const FULLSCREEN_CLOCK_REFRESH_MS = req("FULLSCREEN_CLOCK_REFRESH_MS");
export const HEART_RATE_REFRESH_MS = req("HEART_RATE_REFRESH_MS");
export const DEFAULT_CAMERA_DEBUG_ENABLED = req("DEFAULT_CAMERA_DEBUG_ENABLED");
export const CAMERA_DEBUG_REFRESH_MS = req("CAMERA_DEBUG_REFRESH_MS");
export const GALLERY_METADATA_CAMERA_REFRESH_MS = req("GALLERY_METADATA_CAMERA_REFRESH_MS");
export const DEFAULT_HUD_FIELD_ORDER = req("DEFAULT_HUD_FIELD_ORDER");
export const DEFAULT_HUD_VISIBLE_COUNT = req("DEFAULT_HUD_VISIBLE_COUNT");
export const DEFAULT_HUD_DOCK_COLLAPSED = req("DEFAULT_HUD_DOCK_COLLAPSED");

// Training zones
export const DEFAULT_RESTING_HEART_RATE_BPM = req("DEFAULT_RESTING_HEART_RATE_BPM");
export const DEFAULT_MAX_HEART_RATE_BPM = req("DEFAULT_MAX_HEART_RATE_BPM");
export const POWER_ZONE_DEFINITIONS = req("POWER_ZONE_DEFINITIONS");
export const HEART_RATE_ZONE_DEFINITIONS = req("HEART_RATE_ZONE_DEFINITIONS");
export const HEART_RATE_MAX_AGE_FORMULA_BASE = req("HEART_RATE_MAX_AGE_FORMULA_BASE");
export const PROFILE_HISTORY_SAMPLE_LIMIT = req("PROFILE_HISTORY_SAMPLE_LIMIT");
export const CYCLING_GROSS_EFFICIENCY = req("CYCLING_GROSS_EFFICIENCY");

// Climb banner
export const CLIMB_BANNER_APPROACH_METERS = req("CLIMB_BANNER_APPROACH_METERS");
export const CLIMB_BANNER_MINI_BAR_COUNT = req("CLIMB_BANNER_MINI_BAR_COUNT");
export const CLIMB_CATEGORIES = req("CLIMB_CATEGORIES");

// Route difficulty classification (shared with the Python gallery generator)
export const EQUIVALENT_KM_CLIMB_METERS = req("EQUIVALENT_KM_CLIMB_METERS");
export const DISTANCE_CLASS_THRESHOLDS_KM = req("DISTANCE_CLASS_THRESHOLDS_KM");
export const TERRAIN_CLASS_THRESHOLDS_M_PER_KM = req("TERRAIN_CLASS_THRESHOLDS_M_PER_KM");
export const DIFFICULTY_THRESHOLDS_EQUIVALENT_KM = req("DIFFICULTY_THRESHOLDS_EQUIVALENT_KM");

// Climb detection (leaky-bucket fatigue integrator — see tuning.yaml)
export const CLIMB_FATIGUE_THRESHOLD = req("CLIMB_FATIGUE_THRESHOLD");
export const CLIMB_MAX_FATIGUE = req("CLIMB_MAX_FATIGUE");
export const CLIMB_RESTING_GRADIENT_PERCENT = req("CLIMB_RESTING_GRADIENT_PERCENT");
export const CLIMB_RECOVERY_MULTIPLIER = req("CLIMB_RECOVERY_MULTIPLIER");
export const CLIMB_SMOOTHING_WINDOW_SIZE = req("CLIMB_SMOOTHING_WINDOW_SIZE");
export const CLIMB_MIN_GAIN_METERS = req("CLIMB_MIN_GAIN_METERS");
export const CLIMB_MIN_AVERAGE_GRADE_PERCENT = req("CLIMB_MIN_AVERAGE_GRADE_PERCENT");

// Demo mode
export const DEMO_RIDE = req("DEMO_RIDE");

// Ride recording
export const RIDE_SAMPLE_INTERVAL_MS = req("RIDE_SAMPLE_INTERVAL_MS");
export const RIDE_PERSIST_INTERVAL_MS = req("RIDE_PERSIST_INTERVAL_MS");

// Landing page hero replay
export const LANDING_HERO = req("LANDING_HERO");
